# Docs for the Azure Web Apps Deploy task: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops
# More info on Python, Azure Pipelines, and Azure App Service: https://aka.ms/python-webapps-pipelines

trigger:
- flask_deploy

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '<your-subscription-name>'
  appName: 'service-selector'
  resourceGroupName: 'rg-service-selector-dev'
  packagePath: '$(Pipeline.Workspace)/drop'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Set up Python'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r demo_app/app/requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    resourceGroupName: $(resourceGroupName)
    runtimeStack: 'PYTHON|3.8'
  startUpCommand: 'cd demo_app/app && gunicorn --bind=0.0.0.0 --timeout 600 app:app'